# FAQ

> Argo CloudOps server returns "INTERNAL ERROR" when following logs

This happens when a deployment executes for a long time. Just reissue the logs command to retry. Team is tracking an [issue](https://github.com/argoproj-labs/argo-cloudops/issues/93) to resolve


